language: node_js
node_js:
  - "6.2.1"
env:
  - CXX=g++-4.8
before_install:
script:
  - npm run build
notifications:
  slack:
    rooms:
     - team8:S0sZq9mFA8c6kdIHlGsgqbXY
    on_success: change
    on_failure: always
