language: node_js
node_js:
  - "5.9"
  - "6.1.2"
before_install:
script:
  - npm run build
notifications:
  slack:
    rooms:
     - team8:S0sZq9mFA8c6kdIHlGsgqbXY
    on_success: change
    on_failure: always
